# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_DELIVERY_API_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_API_TOKEN }}
  CONTENTFUL_PREVIEW_API_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_API_TOKEN }}
  CONTENTFUL_MANAGEMENT_API_TOKEN: ${{ secrets.CONTENTFUL_MANAGEMENT_API_TOKEN }}
  CONTENTFUL_OAUTH_CLIENT_ID: ${{ secrets.CONTENTFUL_OAUTH_CLIENT_ID }}
  CONTENTFUL_DEFAULT_ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_DEFAULT_ENVIRONMENT_ID }}
  CONTENTFUL_ALLOWED_HOSTNAME: ${{ secrets.CONTENTFUL_ALLOWED_HOSTNAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
